### ISSUE TITLE
Proposal for Core/Extras Split

### ISSUE THREAD

**Issue by gregdek** [ansible/community#102]
We need a proposal for this, and we need public discussion. We're committed to splitting out the Extras repo into a separate package for 2.2, but we need to work out the details publicly.

**Comment by gundalow** [comment]
[20:47] < jhawkesworth> I know I'm guilty of using extras modules in tests for core modules (integration tests that is)


We will need to watch out for that, though it should be an obvious and quick fail (assuming we don't install the extras package)

**Comment by jhawkesworth** [comment]
So this has been on my mind a bit.  I'm going to dump out some random thoughts here for now.

Lets agree why we are doing this so we have a guide to look back on as we discover stuff.

I think the idea is for extras to become a separately installable thing.  Extras would be something you would add to your ansible controller because you had a particular interest or needed something that isn't generally applicable?

I think the purpose of this is to let extras evolve at a faster pace.  It changes the balance between quality review but lowers the barrier to change.  And we feel this is ok because the processes to ensure quality of the core modules don't change and may even be improved by having a narrower focus.

I think inherent in this is that 'extras' becomes 'optional extras'.  From this its a small jump to the notion that ansible can stand up and do (as yet undefined) useful things without the extras.  Does that sound right?

Advantages
 For contributors 
   just 2 repos to wrangle instead of 3.

For core team members
  narrower focus

 For users
   potentially faster availablity of new modules in easy to consume packaged format

Questions.

By making extras a separate deployable thing, there must be a defacto interface between core and extras.  Does this imply that we are allowing / encouraging multiple sources of extras?
(I know you can chuck what you like into your library/ - and I do - right now but this is different from a packaged set of modules maintained by someone else being available from (say) pip).

I can see multiple extras sort of making sense if other interested groups want to maintain specific module sets and release them to match their own release schedules.  Maintaining a git hub repo of modules is one thing - here's an existing example - https://github.com/F5Networks/f5-ansible but also maintaining a pip package of them is another I suppose.

Are we happy that the current core modules are the right core modules?
Is there anything this IS core that should not be core?
Is there anything that is extras that must become core before a split?

Things that might qualify a module as being core
   meets quality criteria - has tests
   utility - ansible without copy and template would be kinda not much use.  I'd say the same for managing service states and native package management.  But where's the line beyond which modules can only be considered as extras?  I'd argue that win_registry ought to be core for windows as the registry is where a lot of windows stuff is configured (think stuff in /etc in the *ux world) and configuring is definitely at the heart of what ansible is for.

Do we need to discover what modules are getting used now? Would gathering anonymous module usage stats be worth the trouble (or even acceptable to the community).  Is there some analysis we can do, for example using galaxy roles to determine what modules are so utilized that they should become core?  Or is it enough to go with what we have now and make moving modules into core as quick as we can (while maintaining core's quality criteria).

I hope 'asking tricky/dumb questions' constitutes contributing to this.

**Comment by gregdek** [comment]
:)

Lots of good questions here.

I think you've set the table properly re: advantages of splitting out extras, and I think you've hit on most of the pain points, too. To me, the challenges break down into two fundamental categories:

* How do we accomplish the split? And
* What modules end up on each side?

**Comment by buzzsurfr** [comment]
> What modules end up on each side?

For starters, I think any module (or set of modules) that support a single product or service.  F5 is already singled out above, and I think you can include Cloud, Database, Messaging, Vendor Networking, and Web Infrastructure modules.

However, instead of deciding which modules belong in which group, try to place a module based on a set of factors, such as:
 - whether its essential for Ansible to function
 - what level of an instance does the module support (
