### ISSUE TITLE
open source galaxy

### ISSUE THREAD

**Issue by gregdek** [ansible/community#11]
Not sure how we're going to do this, but it's time to start keeping track of this commitment.

**Comment by ksatirli** [comment]
Being able to run our own Galaxy (at one point) will be a great addition! 

Creating roles and sharing them on the (public) Galaxy is sometimes prohibitive. Right now, for us this means we end up with Git constructs in playbooks where Control Masters need to have repo access or we end up with folks bunching roles into a generic repo, thus decreasing maintainability.

**Comment by robynbergeron** [comment]
@ksatirli -- thanks for the feedback.

**Comment by robynbergeron** [comment]
Update:

I am taking this task on. 

Current status: Will be putting together an overview of what the requirements are to get this done, so that we can estimate how long this will take. (Note: this is different from "requirements or wishes for galaxy itself" :smile:)

Will post updates as I have them

**Comment by gregdek** [comment]
ETA for requirements: end of this week

**Comment by chouseknecht** [comment]
Are you looking for a list of the technical things needing to be done?

**Comment by bcoca** [comment]
DONE http://github.com/ansible/galaxy
