### ISSUE TITLE
Testing Working Group Meeting Agenda

### ISSUE THREAD

**Issue by gundalow** [ansible/community#114]
The **Testing Working Group** will be the central point for all things related to testing Ansible, with some overlap with how to make it easier to develop and extend Ansible & modules

In particular this community have the following aims:
- Publicise the testing roadmap and correlate feedback from the community
- Fast track community PRs that are aligned with the Testing Strategy 
- Fast track functional (new modules, bug fixes) PRs that have tests
- Make it easier to add/extend tests
- Be the centralised place for feedback for all things testing related

Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

Tracking document
https://public.etherpad-mozilla.org/p/ansible-testing-working-group

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/MEETINGS.md for the schedule

**Comment by alikins** [comment]
https://github.com/ansible/ansible/issues/16864 - Add test apt,ppa,yum repos to httptester images for integration tests

**Comment by gundalow** [comment]
Hi, I'd like to propose https://duckduckgo.com/?q=1800+UTC&ia=answer Starting Thursday 18th August for the weekly meeting. We need to cater for East Coast & Europe, I hope that works for most people.

+1/-1 welcome :)

**Comment by srvg** [comment]
:+1:  svg on irc

**Comment by rcarrillocruz** [comment]
works great for me.

**Comment by pabelanger** [comment]
+1

**Comment by supertom** [comment]
+1

**Comment by gundalow** [comment]
Hi,

Due to other conflicts I need to move this one hour earlier so it will now be

https://duckduckgo.com/?q=1700+UTC
Hope most can still make that

**Comment by gundalow** [comment]
**Agenda for meeting 1**

  * Welcome!
  * Introductions from Ansible Core Team and Contributors
  * Review of purpose
  * What we already have planned see _Infrastructure Buildout and Changes (Matt Clay)_ on [ROADMAP_2_2.rst](https://github.com/ansible/ansible/blob/devel/docsite/rst/roadmap/ROADMAP_2_2.rst)
  * Poll on what people are interested in 
  * What the community is interested in helping with


As with an of the Community Working Group meetings, please feel free to add your own thoughts and ideas to this ticket so I can add it to the agenda.

**Comment by dagwieers** [comment]
+1

**Comment by gundalow** [comment]
@linuxdynasty has put forward this module to be used as an example of a good module https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/amazon/kinesis_stream.py

**Comment by caphrim007** [comment]
* Is there a way to test modules that use map() and expect a list to be returned? Python 3 changes map() to be an iterator
* as @caphrim007 to show the functional test model he uses for F5 modules

**Comment by robinro** [comment]
PR by @cinerama70 to review/merge. Test for `ansible_os_family` and a related bugfix:
https://github.com/ansible/ansible/pull/17620 and https://github.com/ansible/ansible/pull/17575

In general the test coverage of basic facts could use some more attention.

**Comment by mscherer** [comment]
Sorry I merged https://github.com/ansible/ansible/pull/17620 before realizing you wanted to have it discussed in the meeting. In exchange of me removing a easy discussion during the meeting, I offer  https://github.com/ansible/ansible/pull/17628

**Comment by robinro** [comment]
Thanks @mscherer for the merge. I didn't really want to discuss it but only draw some attention to get it merged and maybe get more tests for the facts code.

**Comment by relaxdiego** [comment]
I'd like to submit my article on Writing Ansible Modules Complete With Tests for feedback by this group. I'll be speaking in AnsibleFest Brooklyn using this content and would like to make sure it aligns with community practices. Feedback will be collated in the next meeting.

The article is at https://www.relaxdiego.com/2016/06/writing-ansible-modules-with-tests.html

**Comment by caphrim007** [comment]
* I think @gundalow asked how I do coverage testing of the f5-ansible modules. I do it using playbooks. I can talk more about it at the next meeting

This is how I do it
https://github.com/F5Networks/f5-ansible/commit/88fb0a423f80955575c5e3945b005a6a067cbc7e

**Comment by relaxdiego** [comment]
Submitting version 2.0.0 of the article for review in the next meeting. Changes are:

* Simplify `main()` and move business logic to separate function
* Take advantage of lessons from Boundaries talk by Gary Bernhardt
* Reference module checklist
* Give credit where credit is due :-)
* Other minor fixes

**Comment by gundalow** [comment]
Do we want a `test_pull_requests` label so we can identify (and therefore fast track) PRs that improve testing? Would people find this useful and help review changes?

**Comment by alikins** [comment]
Wouldn't mind discussing https://github.com/ansible/community/issues/114#issuecomment-236970705 (adding httptester hosted apt/yum/etc repos to reduce test failures from repo connectivity issues)

**Comment by gundalow** [comment]
For discussion on Thursday 20th October

**Prep for repo merge**
* Integration tests moving - 
   * https://github.com/ansible/ansible/tree/devel/test/integration/targets
   * Dropping of `test_` prefix
* `ansible-validate-modules` is now https://github.com/ansible/ansible/tree/devel/test/sanity/validate-modules

**httptester**
After seeing the discussion during Contributor Summit regarding making `httptester` available in non-docker forms Sivel has raised:
https://github.com/ansible/ansible/pull/18107

**Comment by gundalow** [comment]
ACTION: gundalow to find all old references to ansible-validate-modules in google and get them updates

**Comment by gundalow** [comment]
No Testing Working Group meeting today (27th October) instead there will be a discussion around repo merging starting 30 minutes before in `#ansible-meeting`

**Comment by gundalow** [comment]
No Testing Working Group meeting today (3rd November), instead there is a meeting about the repo merge, all welcome.

**Comment by frenzymadness** [comment]
Hi.

I really want to help with Python 3 compatibility for Ansible. I think that good point to start and learn more about Ansible is helping with tests coverage.

I want to ask (here or on the meeting) if there is any roadmap for improving tests coverage of Ansible.

**Comment by gundalow** [comment]
@frenzymadness Thanks for the offer of help, please join us in today's meeting

**Comment by mattclay** [comment]
For discussion on Thursday, November 10th:

https://github.com/ansible/ansible/pull/15470

Specifically, how do people feel about having more yamllint rules enforced for tests?

**Comment by gundalow** [comment]
Add a check for type() instead of isinstance()
https://github.com/ansible/ansible/pull/18439

**Comment by gundalow** [comment]
More details about upcoming repo merge 
Important to review for those looking to contribute to module development https://groups.google.com/forum/#!topic/ansible-project/9WpXraBSLz8

**Comment by gundalow** [comment]
No IRC meetings this week. Next Testing Working Group meeting will Thursday 15th December.

**Comment by gundalow** [comment]
No IRC meetings next week. Next meeting is on Thursday 5th Jan.

**Comment by dagwieers** [comment]
New item for next meeting. Lowering the bar for integration tests by removing silly checks.

See: https://github.com/ansible/ansible/pull/20539#pullrequestreview-19247821

Doing another:
- wait for Shippable (about an hour)
- check results
- find some silly yamllint requirement (no blank lines at the end of a yaml file)
- change branch again
- hunt it down
- commit
- push

This is not really encouraging more integration tests and not valuable time spent on Ansible. I'd say lower the bar and remove silly requirements like this. Tests need to be functional, correct and complete, not comply to arcane cosmetic requirements and waste my time.

**Comment by alikins** [comment]
https://github.com/ansible/ansible/pull/20944

I'd like to see ansible-test ignore files not in git by default.

**Comment by gundalow** [comment]
Ansible Core 2.1.5RC1 and 2.2.2RC1 are available for testing
https://groups.google.com/forum/#!topic/ansible-devel/VnHIVtzuyzs

**Comment by alikins** [comment]
I'd like to see 'ansible-test sanity' run all test and then report all failures instead of exiting on first failure.
No pr yet, but if that is reasonable I can implement it.

**Comment by alikins** [comment]
I have a branch that adds a '--lint' option to 'ansible-test sanity' that just displays pep8 results in a format closer to standard pep8.

The intention is to make it easy to use 'ansible-test sanity' output with tools like the 'syntastic' vim plugin. 

If there is interest, I can start adding that to other sanity tests as well. Maybe example syntastic setup as well.

**Comment by dagwieers** [comment]
I still think we need to make a careful selection of what we think is essential in PEP8, and the stuff that we can leave up to those who care to spend their free time doing. So distinction between mandatory and optional. (Like the trailing newline is, blank lines, the commented lines, ...)

We are now not enforcing everything in PEP8 either because some of it is debatable (or just not important or flat out annoying :-)).

**Comment by sivel** [comment]
@dagwieers that is an incorrect assessment of our stance on coding style.  All new files must adhere to full pep8 with the exception of E402 and 160 char max line length.  It is a goal to get all files there, but due to older files being so far out of "compliance" with our new coding style guidelines, they are being ignored to some level while we work through them.

The agree upon coding style as well as implementation details can be found at https://github.com/ansible/proposals/issues/50

Effectively, we have decided that all but E402 (and a max line length of 160 characters) are essential, and we have no plans on excluding anything else.  As such, they will all be mandatory.

**Comment by dagwieers** [comment]
@sivel I wasn't making an assessment of our stance on coding style. I was proposing we don't implement everything. Since you already have 2 exceptions (so it isn't full PEP8 to begin with), you could opt to have 4 or 5 exceptions instead.

-  Insisting a blank line at the end of a file means people have to modify their editors for this project. Trailing newlines are usually removed, not added. (Even Jinja2 removes them by default, without asking)
- Requiring '#' to be indented with the code makes sense for inline comments, but does not make sense for commented code (code that is commented because it has been disabled on purpose). If one cannot make the distinction between commented examples and disabled code, that does not increase readability, quite the contrary.

These things shouldn't matter and have nothing to do with code readability. I don't know who thinks having a trailing newline is useful or a sensible thing to do. I don't mind if that person adds trailing lines where they see fit, but don't bother the rest of the community with pedantic rules like this.

And people are allowed to change their minds (even after something has been decided). Sometimes that is called experience or even intelligence ;-) You seem to leave no room for objection or change of mind in your reply.

**Comment by sivel** [comment]
There isn't.  It's been agreed upon, and implementation is in progress.

**Comment by dagwieers** [comment]
What isn't there ?

**Comment by allanice001** [comment]
Woudn't a basic .editorconfig file at project root help ?

```
# -*- mode: conf-unix; -*-

# defaults
[*]
insert_final_newline = true

# 4 space indentation
[*.{ini,py,py.tpl,rst}]
indent_style = space
indent_size = 4

# and travis does its own thing
[.travis.yml]
indent_style = space
indent_size = 2
```

**Comment by dagwieers** [comment]
The fact that we are even discussing this, and @mattclay is copy&pasting these errors in GitHub comments and people have to go back and fix this is so absurd. Nobody ever considered the gains vs the pains ? Contributor frustration for things one cannot simply explain ?

I am not questioning PEP8 in general, a lot of rules do make sense (and because of that, people are willing to put effort in). But I contest this is an all-or-nothing decision. Only @bcoca made sensible remarks wrt. these rules IMO.

Fact is that few new contributors will come and tell you this, they will simply not bother. There are a lot more important things we _do_ want people to know and do wrt. modules and code, and believe me, trailing newlines and other silly requirements are just big distractors to what truly matters. But I guess since you can automate this, and not the rest it's fine to bother everybody else with it.

So I got that out of my system. Good night !

**Comment by mattclay** [comment]
Just to address a few specific points from earlier comments:

> Insisting a blank line at the end of a file

There are two related PEP 8 guidelines being enforced:

W292 no newline at end of file
W391 blank line at end of file

The newline at the end of file is a line terminator rather than a line separator. To be considered a blank line, there must be 2+ consecutive newlines at the end of the file.

Enforcing W292 leads to a cleaner diff for future changes that add to the end of the file.

> Requiring '#' to be indented with the code makes sense for inline comments, but does not make sense for commented code

The relevant PEP 8 test is:

E115 expected an indented block (comment)

Generally, commented out code should be avoided. For the rare case where it is desirable, the potential drop in readability for that code should be outweighed by the improved readability of properly indented non-code comments, which occur at a much higher frequency.

> people have to go back and fix

Adding more tests to CI will inevitibly lead to more CI failures. That's why making tests easier and faster when running locally is important. To help deal with this, I'm working on improving messaging for various CI failures. When possible, I'd like CI failures to explain not only the failure, but how to run the test locally.

**Comment by mikedlr** [comment]
regarding pep8;  could ansibot, for example, run autopep8 on new commits and then do a fix commit before sending new PRs off to shippable for testing?  Since most of the rules are being enforced by flake8 so the commits won't be accepted otherwise, this could only reduce pain for committers.

A script that was easy to set up on local git repos to run flake8 / some simple test from a hook before a git commit would also help more regular committers.

**Comment by jctanner** [comment]
ansibot is not a code linter nor a CI framework. Almost all of the tests that run in shippable can be run locally.

**Comment by pabelanger** [comment]
FWIW: by using tox (https://tox.readthedocs.io/en/latest/) as the entry point for locally testing, it is very easy to add a pep8 / flake8 envlist to your tox.ini[1]. Then you get to bikeshed on which things to ignore[2]

[1] https://github.com/openstack-dev/cookiecutter/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tox.ini#L15
[2] https://github.com/openstack-dev/cookiecutter/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tox.ini#L38

**Comment by mikedlr** [comment]
I'd like to propose activating cloud integration tests in continuous integration.  Last weekend I cleaned enough of them up that they run more or less cleanly for me locally (see #22499).  There were many problems showing that most of the tests were not in a runnable state.  With some more work they could be made to be reasonably stable.  If they ran on checkins to devel at least then it would be much more likely that they would be maintained in future.  I'll try to be in thursday's (14th March) testing meeting but if I fail to make it I will read the log anyway.

**Comment by dagwieers** [comment]
I'd like to discuss a structured way to reuse tests for both normal mode and check-mode testing, and also discuss the use of YAML anchors and references for doing idempotency testing. Since I would like to redo all the Windows integration tests (some are simply missing) I would like to get approval on the preferred mechanism.

See this example : https://github.com/ansible/ansible/pull/22611/files#diff-9bdd58936ad3aaccf0f2daa7c4a385e1R1

**Comment by gundalow** [comment]
When do we want to remove Ubuntu 12.4 LTS testing which goes EOL in April

**Comment by mattclay** [comment]
Tests for python 2.4 have been removed from devel. Caution is required when making fixes which must be back ported to stable branches, since they still have the python 2.4 requirement.

**Comment by Shaps** [comment]
Is it best to have https://github.com/ansible/ansible/issues/18181 as code-smell tests or in validate-modules?

**Comment by mscherer** [comment]
Ubuntu 12.04 will have a Extended LTS it seems ( https://insights.ubuntu.com/2017/03/14/introducing-ubuntu-12-04-esm-extended-security-maintenance/ ). Not sure on the impact of testing, but I guess we can do like RHEL 5 and drop it ?

**Comment by mattclay** [comment]
Use `flake8` instead of `pep8`: https://github.com/ansible/ansible/pull/22820

**Comment by sivel** [comment]
pep8 current to legacy:

https://github.com/ansible/ansible/pull/22891
https://github.com/ansible/ansible/pull/22911

**Comment by Shaps** [comment]
still some discussion about: #22744

**Comment by gundalow** [comment]
Discussion: How to deal with PRs that fail CI *after* merge

Consider the case:
PR created
Reviews/updates
Still passes CI
**Time Passes**
CI is made stricter (e.g. pep8 or validate-modules)
PR merged (as it's green)
Merge now fails updated tests

Seen this twice today

Do we need to do rolling reruns CI on `status:success`?

**Comment by gundalow** [comment]
Ansible 2.3 RC3 has been released https://groups.google.com/forum/#!topic/ansible-devel/X8sYLl-ZuTY

We welcome your feedback, after all, we can only fix what we know is broken. If you spot any issues please raise via https://github.com/ansible/ansible/issues/new

Thanks again for your help

**Comment by resmo** [comment]
- Automated CloudStack testing (https://github.com/ansible/ansible/pull/20552)
  - State of integration into ansible-test?
  - Who doing what, how can I help?

**Comment by gundalow** [comment]
Ansible 2.3.0 FINAL has been released. Thank you for all your help with this release
https://groups.google.com/forum/#!topic/ansible-project/aKnggI-Y8dk

**Comment by mattclay** [comment]
If anyone is interested in joining the Contributors Summit (in person or remote), ping @gundalow directly.

**Comment by gundalow** [comment]
# NO MEETING: Thursday 20th April

# NEXT MEETING:  Thursday 27th April

**Comment by gundalow** [comment]
Ansible `2.2.3 FINAL` released, `2.1.6rc1` and `2.3.1rc1` available for testing

All of these releases address at least one CVE (listed below). Users of 2.2.x should upgrade to 2.2.3 as soon as possible. The CVE impacting 2.1.x and 2.3.0 is MODERATE in nature, however users should look to upgrade as soon as the final releases are done. 
https://groups.google.com/forum/#!topic/ansible-devel/etlpnJDerY0

**Comment by gundalow** [comment]
**Ansible Contributor Summit 4 (Part of AnsibleFest 2017 London)**

We are happy to announce our fourth Ansible Contributors Summit!
AnsibleFest London (http://www.ansible.com/ansiblefest) will be on Thursday 22nd June, and the Contributor Summit will be held on Wednesday 21st June, from 9:30am to 4pm (time subject to change).

Contributors Summit is a day-long working session with the core team and key contributors to discuss important issues affecting the Ansible community. You can participate in person or online

Proposed topics: https://public.etherpad-mozilla.org/p/ansible-summit-june-2017

See https://groups.google.com/forum/#!topic/ansible-devel/stUITiM6hMs for more info

**Comment by gundalow** [comment]
**Ansible Contributor Summit 4 (Part of AnsibleFest 2017 London)**

Agenda for Contributor Summit has finalised can be found at https://public.etherpad-mozilla.org/p/ansible-summit-june-2017-agenda.

As a reminder, it will be in `#ansible-meeting` and BlueJeans

Note that there are sub pages for each topic. It's on the sub pages where you can add any topics there, rather than on the main agenda page.

**Comment by gundalow** [comment]
Due to Contributors Summit & AnsibleFest

# NO MEETING: Thursday 22th June

# NEXT MEETING:  Thursday 29th June

**Comment by dagwieers** [comment]
Please discuss during your next meeting what information can be added to:
https://github.com/ansible/community/tree/master/group-testing

And if there's any collaboration information you want to share on the wiki:
https://github.com/ansible/community/wiki/Testing

**Comment by gundalow** [comment]
Use pycodestyle instead of pep8  https://github.com/ansible/ansible/pull/25947

**Comment by gundalow** [comment]
Test dependencies
`test/runner/requirements/integration.txt` is growing and contains packages needed only for specific tests, rather than what's needed to just run `ansible-test`

Matt Clay has proposed that we put requirements in `test/integration/targets/*/requirements.txt`

Should this logic also be extended to unit tests?
Do we need to require and document that all unit tests gracefully fail if the required dependencies are not installed?
Though perhaps for Shippable runs we need to make it a fatal error

**Comment by gundalow** [comment]
**test_win_group*.yml** Do we still need these files, if not can we delete them?

**Comment by gundalow** [comment]
Document codee Coverage https://codecov.io/gh/ansible/ansible/

**Comment by pilou-** [comment]
About
> test_win_group*.yml Do we still need these files, if not can we delete them?

mattclay [wrote](https://github.com/ansible/ansible/pull/25229#issuecomment-306204471):
> The Makefile is the legacy method of invoking tests that predates ansible-test. Instead of updating the Windows related targets in the Makefile (and renaming their associated playbooks), they should be removed.

[and](https://github.com/ansible/ansible/pull/25229#issuecomment-306675934):
> The test_win_group*.yml files should be removed as well, as they're only used by the windows targets in the Makefile.

**Comment by dagwieers** [comment]
For testing the **win_uri** module (and eventually the **uri** module as well) we would like to look at using httptester. This was deemed the preferred way during some discussion (don't have a reference at hand).

For Windows that would mean that the VMs need to be able to connect the the httptester docker network. As a result, we will leave the idea to set up our own http listener process (https://github.com/ansible/community/issues/153#issuecomment-307416056).

**Comment by dagwieers** [comment]
For the new *xml* module, we need lxml provisioned. For the docker images, this is already the case, but for the VMs (FreeBSD, MacOSX) lxml is still missing.

**Comment by gundalow** [comment]
https://meetbot.fedoraproject.org/ansible-meeting/2017-06-29/testing_working_group.2017-06-29-17.00.html
https://meetbot.fedoraproject.org/ansible-meeting/2017-06-29/testing_working_group.2017-06-29-17.00.log.html

**Comment by gundalow** [comment]
`test_pull_requests` label. 
If we want to use this label to find PRs with tests should we stop `test/sanity/pep8/*.txt` from getting that label?

**Comment by willthames** [comment]
@gundalow maybe just exclude test/sanity completely if you want to find PRs that are testing themselves rather than testing everything, if that makes sense.

**Comment by gundalow** [comment]
Do we want to start testing `fedora26`?

**Comment by mattclay** [comment]
I'm updating our Fedora CI testing. My current plan is to:

- Remove testing of Fedora 24 with python 2.
- Remove testing of Fedora 25 with python 2.
- Add testing of Fedora 25 with python 3.
- Add testing of Fedora 26 with python 3.

Fedora 24+ default installations are python 3.5+ only. These changes update CI to match.

**Comment by pilou-** [comment]
Failure of `copy`module integration tests: [#25672](https://github.com/ansible/ansible/pull/25672).

**Comment by pdellaert** [comment]
Can we add a short discussion on running `ansible-test` inside an environment that requires a proxy? 

Specifically when running `ansible-test ... --docker`, the docker images are unable to run commands that require external access (for instance pip). 

Suggestion: expose `*_proxy` environment variables to all containers.

Not sure if tox supports this, btw, i've seen some issues there (could be related to something else)

**Comment by pdellaert** [comment]
@pilou-, There's two aspects :
- **Test infrastructure aspect:** containers being able to install stuff through pip or apt/yum, or tox being able to use proxy
- **Tests themselves:** Tests needing to connect to the outside world through a proxy, for instance to connect to external APIs (mainly integration testing might be impacted here)

I'd suggest support a proxy within the test infrastructure.

The tests themselves is a different story, these are indeed a lot more complicated and will depend significantly on a test per test basis (some might require a proxy, while others might not because connections are local)

A rough approach could be (if enough support/interest, of course):
- **Stage 1:** Provide test infrastructure support for proxy, through a new flag in ansible-test (--proxy), this flag sets the http_proxy, https_proxy and the apt/yum proxy values within the docker containers (-e..., as far as i know both Ubuntu and CentOS base containers support an -e setting to configure apt or yum proxy). The flag also configures tox to use the proxy if tests are run through tox.

- **Stage 2:** For integration testing itself: Expand the test system to allow specifying a boolean in the test cases 'requires_proxy', which would push the proxy setting from Stage 1 into the facts used by the integration playbooks.

**Comment by pilou-** [comment]
To sum up the meeting:
- copy integration tests fails ([PR](https://github.com/ansible/ansible/pull/25672)) when managed and controller aren't the same (CI use one host for managed and controller).
  - that could be solved using different filename prefixes ("local" for local file/"remote" for local file)
  - Pilou will update the pull requests.
- test infrastructure support for proxy:
  - pdellaert will provide environment variables, then cc mattclay
  - mattclay will create a PR with implementation, then pdellaert will be able to test it
- Pylint tests:
  - abadger1999 has been doing quite a bit of recent code cleanup around Pylint failures: `undefined-variable` test is enabled
  - abadger1999 is working on cleaning up wildcard imports.
  - Volunteers for cleaning up existing pylint issues can reach out to abadger1999 anytime :-)

**Comment by mattclay** [comment]
@pilou- Thank you for the excellent summary.

**Comment by pilou-** [comment]
I would like to discuss cloud/packet integration tests (https://github.com/ansible/ansible/pull/23127) at the next meeting.

**Comment by pdellaert** [comment]
On my action point: 
ansible/ansible#27697

**Comment by Spredzy** [comment]
I would like to discuss the addition of the latest macOS 10.12 image in the CI pipeline (current 10.11)

**Comment by gundalow** [comment]
**Ansible Contributor Summit 5 (Part of AnsibleFest 2017 San Francisco)**

When: 2017-09-06:
Notes: https://public.etherpad-mozilla.org/p/ansible-summit-september-2017
Event will be in person + online (Video + IRC)

Agenda is open for topics for the next Contributors Summit

Please add (and vote `+1`) for any topics.

**Comment by Akasurde** [comment]
PR needs review:
* https://github.com/ansible/ansible/pull/26309 - Add testcases for github_issue
* https://github.com/ansible/ansible/pull/26859 - Refactor code and testcase for find_host_by_cluster_datacenter

**Comment by gundalow** [comment]
**NOTE:** meetings are canceled for the week Aug 21st to 25th due to 'all hands' meeting for the core team. We will resume normal schedule after that.

**Comment by mattclay** [comment]
What should qualify as a destructive test? Existing [documentation](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/testing_integration.rst#destructive-tests) covers this, but we may want to [consider changing the criteria](https://github.com/ansible/ansible/pull/28520#issuecomment-324210179).

**Comment by gundalow** [comment]
**NOTE:** meetings are canceled for the week September 4th through 8th due to AnsibleFest San Francisco. We will resume normal schedule after that.

**Comment by gundalow** [comment]
Now that 2.4.0 has been released, it seems like a sensible point to move to a fresh agenda
https://github.com/ansible/community/issues/248

NO MORE COMMENTS HERE PLEASE
