### ISSUE TITLE
ansible-playbook-sudo

### ISSUE THREAD

**Issue by naaga12** [ansible/community#146]
Hi,

Can any please let me know why to use "-sudo" flag in ansible-playbook command line.

Thanks,

**Comment by gundalow** [comment]
Hi,
`ansible/community` is a place to track contributions, rather than get support.

Joining `#ansible` on Freenode IRC may be a better place, 
Have a look at https://github.com/ansible/ansible#get-involved for more details


I don't fully understand what you are trying to do, though the following may be of use:

http://docs.ansible.com/ansible/become.html
http://docs.ansible.com/ansible/playbooks_intro.html#basics
