### ISSUE TITLE
How to Run a Working Group

### ISSUE THREAD

**Issue by gregdek** [ansible/community#164]
Need this document for the new SIG structure. Should include:

* How to request a SIG
* How to request a mailing list (even though this is just googlegroups)
* How to register an IRC channel (with meetbot in it)
* How to run an IRC meeting
* Etc.

This is a good document to steal from:

https://github.com/kubernetes/community/blob/master/sig-governance.md#sig-creation-procecure

**Comment by robynbergeron** [comment]
@gregdek Is this stuff that should be linked to / contained in #180 ? 

(Also, should this be "working groups" and not SIGs?)

**Comment by robynbergeron** [comment]
Labelling for discussion in Community WG meeting today. (Pretty sure this can be closed because we now have the "how to get a WG" documentation (from #180).)

**Comment by robynbergeron** [comment]
Okay, so turns out we think we have some minor additional things to add here. So not ready to be closed. 

Notes from meeting to jog @gregdek's memory:

10:23 <@rbergeron> I think this is largely done by way of 180 being merged - yes / no?
10:23 <@gregdek> Hmmmmmmmm not sure.
10:24 <@rbergeron> Or do you still want to go through the kube link in there to check for other things?
10:24 <@gregdek> I mean, on the one hand, the point of a WG is to run it how you want and provide infra to do so.
10:24 <@gregdek> On the other hand, some pointers are probably useful, and we really don't provide those.
10:24 <@gregdek> "how do i run a meeting?"
10:25 <@gregdek> "how do i use irc effectively to communicate with my wg?"
10:25 <@rbergeron> "what do i need a working group for"
10:25 <@gregdek> "what about mailing lists?"
10:25 <@gregdek> I mean, this is probably just a one-pager faq kinda thing.
10:25 <@rbergeron> "if i'm making the working group / handling the request, what is the checklist of things i need to 
                   do?" :)
10:25 <@gregdek> I don't think we want *too* much more, but a bit more than what we've got.
10:26 <@gregdek> Heh.  That too.
10:26 <@rbergeron> "can i just join someone else's working group?"
10:26 <@gregdek> Oh, that is a good one.
10:26 <@gregdek> That's a very good one.
10:26 <@rbergeron> Okay, want me to just copy this random list into the issue and let you go from there?
10:26 <@gregdek> "How do I join a WG?"
10:26 <@gregdek> Yep, sounds good.
