### ISSUE TITLE
JBoss Working Group creation request

### ISSUE THREAD

**Issue by wbrefvem** [ansible/community#188]
WORKING GROUP NAME:    JBoss

WORKING GROUP PURPOSE:
This group's purpose is to review, coordinate, and suppot work on Ansible as it relates to JBoss-related technologies (JBoss AS, Wildlfy, Infinispan, etc.). Initial goals would be to expand the deployment capabilities of the current JBoss module, and next steps would be either to expand the module to support the full range of JBoss management capabilities or develop other modules to do the same.

AT LEAST TWO INITIAL WORKING GROUP MEMBERS:
IRC: wbrefvem / GitHub: @wbrefvem
IRC: jjunior / GitHub @jairojunior
IRC: wolfantec / GitHub: @Wolfant

**Comment by gregdek** [comment]
Hi @wbrefvem @jairojunior @Wolfant:

This WG has been created and all members have been added/invited to the ansible/community team.

IRC channel is #ansible-jboss. jjunior and wolfantec have been given op; wbrefvem, you have not since your freenode nick is unregistered (might want to fix that).

You should have wiki space and your own label for issues/PRs. Let us know if you have any questions!

**Comment by wbrefvem** [comment]
@gregdek I've registered my nick. If I could receive op as well, that would be dandy. :)

**Comment by gregdek** [comment]
Done. :)
