### ISSUE TITLE
Clean up / move Community WG stuff (wiki / readme.md)

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#199]
The Ansible Community WG wiki page is empty.

The @ansible/community [readme.md](https://github.com/ansible/community/) has lots of stuff on it. But it is also labeled the "community working group" when ... I guess we should have it really be more like, "Community... Stuff." or something. 

In any case: for consistency / less confusion, we should consider updating the structure somehow; if nothing else, we should clean up some of the old things in the readme.md.

**Comment by robynbergeron** [comment]
Also, note that we do have [a readme](https://github.com/ansible/community/tree/master/group-community) in the group-community path, which is more akin to other things. So I think this is mostly "clean up the old thing and make it less "cwg" specific. And put things on the wiki. :D

**Comment by dagwieers** [comment]
Yeah, so we differentiated the Github repository and the Wiki. Since there are teams that object to using a Wiki, it's nice to have at least one location where we have an overview. The idea was to mimic what the Kubernetes community was doing. And they generate the SIG README pages and keep it mostly for the generic information related to each SIG. Pretty much the way I designed it too.

My preference is to generate it as well similarly to what Kubernetes is doing. Which means every group will have the same metadata in that README (plus some custom stuff they can add at the end of the file).

**Comment by robynbergeron** [comment]
notes from meeting:

10:58 <@rbergeron> This is mostly that community/readme.md has ... some stuff that is needed, other stuff that can probably go into 
                   group-community/readme.md + wiki
10:58 <@gregdek> dag: I did take the bait. It was just earlier in the meeting and you didn't see it. :)
10:58 < dag> gregdek: I meant resmo :-P
10:58 <@gregdek> OHHHH sorry
10:58 <@gregdek> rbergeron: yep, that's just some ugly loose ends right there, think it just needs doing
10:59 <@rbergeron> and we probably need to do some cleanup here. gregdek: it might be sort of related to your working-group info and maybe you want to 
                   stab at it?
10:59 <@rbergeron> so that we don't rework it while you're ... reworking the other thing in overlapping / weird ways?
10:59 <@rbergeron> I think there is probably stuff on the existing community/readme.md that could go in that spot. 
10:59 <@gregdek> Yeah, I think this is all me for right now.
10:59 <@rbergeron> that working-group how-to stuff, to be clear
11:00 <@rbergeron> okay. I'll assign it to you
11:00 <@gregdek> sigh :)

**Comment by robynbergeron** [comment]
Note: probably related / intertwined with #164 (how to run a working group)

**Comment by thaumos** [comment]
I'd love to see something like a wiki or readmes... there are just so many issues it's getting overwhelming!
