### ISSUE TITLE
Better support for newcomers and fresh maintainers

### ISSUE THREAD

**Issue by robinro** [ansible/community#202]
Some aspects could be improved to make it easier for newcomers to join and have contributors become active community members/maintainers/...

* Have a "Newcomer" working group with weekly meetings for new contributors
  * invite all "first-time contributors" that open PRs to this meeting and help them get their stuff merged quickly
  * neither the "core" nor "community" meetings are appropriate for that imo since they discuss too many internal things that confuse newcomers
* Make the bot nicer to newcomers, write a welcoming message, thank for PR, invite to IRC ...
* ensure maintainers are active
  * if a maintainer does not respond to a PR after several weeks:
    * notify other maintainers of the namespace and allow them to shipit
    * offer the PR author to take over as maintainer (maybe require >3 merged PRs?)

**Comment by robinro** [comment]
cc @gregdek @robynbergeron 

These are some ideas that came up when introducing new people to use/contribute to ansible.

Maybe we can discuss this further in a cwg meeting? I can be there next Wednesday.

**Comment by gregdek** [comment]
@robinro some good ideas here, probably deserving of separate tickets.

I won't be at this Wednesday's community meeting since I'm on PTO -- would like to be present to discuss. Maybe the week after? Or we can maybe just have an out-of-band convo on the #ansible-community channel whenever I'm around.

**Comment by gregdek** [comment]
Sorry I haven't been around more @robinro -- if you can attend this Wednesday's meeting, we can discuss in detail.

**Comment by gregdek** [comment]
Thanks again for this @robinro. We discussed in the CWG today. Logs below. Basic takeaway: would you be interested in being one of the founding members of the Newcomer WG, and is there a good time to schedule for further discussion?

Log below.

<•gregdek> Greg DeKoenigsberg Next:
1:09 PM #202, Better support for newcomers and fresh maintainers. By robinro.
1:09 PM Who I was hoping would be here, but alas. 
1:10 PM R<•rbergeron> Can we just discuss this more in the issue until we can have a meeting? Or ask if we can meet up at a time that works better for robinro and have a not-regularly-schedule time to chat?
1:10 PM G<•gregdek> Greg DeKoenigsberg There's some good stuff in here, so worth drilling down into.
1:10 PM And yes.
1:11 PM Do we want to discuss a bit here now and drop that into the issue for robinro's consumption, with a separate scheduled meeting with robinro?
1:11 PM My big thing: I think a "newbie working group" is a really good idea, and if robinro is interested in helping shepherd it, that's awesome.
1:12 PM R<•rbergeron> I think it is as well -- and as always... if someone wants to do it, I don't have any reason why they shouldn't be able to :)
1:12 PM G<•gregdek> Greg DeKoenigsberg LOL, right.
1:12 PM OK, so.
1:13 PM 1. Encourage him to start the newcomer wg with our full support / participation.
1:13 PM R<•rbergeron> I think it's probably linked a bit to another issue that maybe gundalow had filed about easyfix things -- can't remember if that's an issue or just a thing we had chatted about.
1:13 PM G<•gregdek> Greg DeKoenigsberg Yeah, I think it is related.
1:13 PM R<•rbergeron> I think we could probably help out on that with blog on ansible.com also
1:13 PM G<•gregdek> Greg DeKoenigsberg Or should be.
1:13 PM G<•gundalow> sloop +1
1:13 PM C<chouseknecht> seems like it's more of a... "I submitted a PR, and it hasn't gotten any attention. Now what do I do?" meeting.
1:13 PM G<•gregdek> Greg DeKoenigsberg It may be some of that, yes.
1:14 PM And sometimes, the answer is "go to the public core meetings". But often, it's not, and we kind of don't have a good answer.
1:14 PM But the notion of having a working group geared specifically to new contributors who don't know the lay of the land yet is useful...
1:15 PM ...particularly because it forces us to continually reevaluate things from the n00b perspective.
1:15 PM Which becomes *much* harder the more you already know about the project.
1:15 PM C<chouseknecht> agree, helping people get started is good.
1:15 PM R<•rbergeron> yep.
1:16 PM G<•gregdek> Greg DeKoenigsberg And while we continue to iterate over our contribution documents, there's still no good place for people to go to get answers.
1:16 PM G<•gundalow> sloop I like the idea of having a place for n00b questions to continually be asked and make up update docs and processes
1:16 PM G<•gregdek> Greg DeKoenigsberg (Well, not a place that's geared to n00bs, anyway.)
1:16 PM R<•rbergeron> Or generally: new ideas that ... don't quite have a home in which to flourish or framework or whatever.
1:16 PM etc.
1:17 PM G<•gregdek> Greg DeKoenigsberg Yup.
1:17 PM OK, so. I'll add all this to the issue and ask for robinro's interest in helping with that n00b group.
1:17 PM And ask to set up a time to chat further that works for him.

**Comment by robinro** [comment]
Thanks @gregdek and all for discussing this and sorry I couldn't make it.
I don't think I have the time to head up the newcomers wg.
Also (if I would find the time in the future) this job definitely needs commit rights (which I don't have) since one of the main tasks in my view would be to quickly merge simple PRs and adapt docs to assist newcomers.
Let's try to find a time in direct communication to discuss this more.

**Comment by lwm** [comment]
> if a maintainer does not respond to a PR after several weeks
> notify other maintainers of the namespace and allow them to shipit
> offer the PR author to take over as maintainer (maybe require >3 merged PRs?)

Yes, this! As someone who came around to pick up some Linode related tickets, when maintainers were barely around (no blame, it's fine, but this was the case), it generally took ~10+ days to get anything reviewed. I also had to ask on #ansible-devel (multiple times), the mailing list and try to get the stuff seen to on #ansible-meeting (I failed to turn up that one time though!). It's fine really, Ansible has a huge backlog and finite resources, and there are a lot of nice people around and things got moving eventually, but I guess other first time contributors are leaving who are not as stubborn as me ;)
