### ISSUE TITLE
Container Agenda September

### ISSUE THREAD

**Issue by chouseknecht** [ansible/community#237]
- Pre-bakes are in `develop`. What's next on the road to 1.0.0?
- PR #719 - adds `build_command` directive
- Jag and House discussed the following roadmap items:
    - Enable idempotence for faster builds.
        - On rebuilds, when we detect that an existing image layer does not match the expected hash, we throw it away, and rebuild from that point. This forces Ansible to re-run all tasks in the role.
        - The same for failed builds. We throw away the container, and on restart force the complete re-run of all tasks in the failed role.
    -  Build an Ansible Service Broker (ASB) deployment engine
    -  Create multiple, simple working examples similar to Jag's "Hello World" demo from AnsibleFest 
    -  Get pre-baked conductor images passing RedHat Security Scan, and pushed into RedHat Container Catalog
    - Create daily pre-bake, scanning, and pushing of images in Travis
    - Create a 'best practices' guide for deploying

**Comment by gundalow** [comment]
## Ansible Contributor Summit 6 (Part of AnsibleFest 2018 Austin, Texas)

As part of http://www.ansible.com/ansiblefest

* AnsibleFest Austin will be on both Tuesday 2nd and Wednesday 3rd October 2018
* The Contributor Summit will also be over two days, on Monday 1st and Thursday 4th October, from 9:30am to 4pm (time subject to change).

### This is your event

Ansible succeeds because of its community, and this contributor summit is for you. If you have any topics to discuss, large or small, please be sure to post those topics on the etherpad. For topics that other had added please vote by adding +1

https://etherpad.openstack.org/p/ansible-summit-october-2018 

Please see https://groups.google.com/forum/#!topic/ansible-devel/ivrpVbLya8g for further info

### Attending in person

We realize that not everybody can attend in person, which is why we’ll again be arranging a video conference and a meeting time on IRC in #ansible-meeting to encourage remote participation. This has worked very well for the past Contributor Summits. We’ll be sending out an email with the information for remote participation about a week before the Contributor Summit. 

If you want to attend in-person please sign up at: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 

After signing up you'll receive an email from Eventbrite with a discount code for AnsibleFest Austin. 


### Attending remotely

Please add your name at the bottom of this etherpad: https://etherpad.openstack.org/p/ansible-summit-october-2018 

### Call to action

1) Add ideas to https://etherpad.openstack.org/p/ansible-summit-october-2018 
2) Attending in person: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 then use discount code to sign up to AnsibleFest
3) Attending in person OR virtually: Add your name to the end of https://etherpad.openstack.org/p/ansible-summit-october-2018 
4) Happy automating!

### Questions?
Thanks for all of your contributions to Ansible, and we hope to see you in Austin! And if you have any questions at all, please let us know. 

Speak to `gundalow` on Freenode, or anyone else in `#ansible-devel`
