### ISSUE TITLE
Azure Working Group agenda - Nov 2017-Jun 2019

### ISSUE THREAD

**Issue by nitzmahone** [ansible/community#281]
The Azure Working Group manages Ansible modules for Azure cloud. The group meets weekly on Thursdays at 00:00 UTC (that's Wednesday for the Western Hemispehere - see calendar)

More information about the Azure Working Group:
https://github.com/ansible/community/tree/master/group-azure

Feel free to add your questions to this ticket to be discussed during the upcoming meeting.

**Comment by nitzmahone** [comment]
After some discussion with Laurent on https://github.com/ansible/ansible/pull/33624, there are some low-hanging fruit changes we should make for at least 2.5 (if not backport to 2.4 as well) that should decrease the incidence of breaking changes due to SDK updates:
* all modules should pin their client/models to a specific REST API version; most of the recent breakages have been when a new REST API version was introduced that changed arg ordering or required args, where the old version is still available and would continue to work without changes.
* minimize/remove shared client objects; each module should use the `get_mgmt_svc_client` call directly to request a client with a specific version instead
* minimize/remove SDK calls that use positional args (use kwargs for all constructors and SDK methods where possible); the arg ordering is apparently not guaranteed stable between REST API versions

Also determine if/how we want to handle SDK version pinning going forward via `requirements-azure.txt` in the absence of a pinned-version of the `azure` metapackage.

This would be considered bugfix/stabilization behavior and would not be subject to the 2.5 freezes on 15/30 January, so no rush here.

**Comment by nitzmahone** [comment]
Thought I remembered hearing that Zim was working on a big batch of SQL modules; wasn't sure if that was just around Azure, or general SQL Server modules. If the latter, we should discuss design and client library choices...

**Comment by kyliel** [comment]
@nitzmahone , Zim is working on Azure SQL.

**Comment by kyliel** [comment]
Propose topic for 1/4/2018: Final plan for upcoming 2.5; Ansible + Azure python SDK

**Comment by gundalow** [comment]
The 2.5 freeze dates (merge deadlines) have been pushed out by a week.

Please see updated dates 
https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_5.rst

To see whats change please see https://github.com/ansible/ansible/commit/1826c27e6841eb313dc3a05dc7f19c96e42c7fbf

**Comment by nitzmahone** [comment]
Azure stack support (eg https://github.com/ansible/ansible/pull/33946) - #33897 includes a change that explicitly breaks Azure Stack support for anything that's using storage (https://github.com/ansible/ansible/pull/33897#issuecomment-354139388). 

Need to figure out what's realistic (if anything) for supporting Azure Stack, because if we can't test it, it's going to break.

**Comment by nitzmahone** [comment]
@zikalino in an email requested to discuss facts module RETURN value changes/deprecation

**Comment by gundalow** [comment]
## Ansible Contributor Summit 6 (Part of AnsibleFest 2018 Austin, Texas)

As part of http://www.ansible.com/ansiblefest

* AnsibleFest Austin will be on both Tuesday 2nd and Wednesday 3rd October 2018
* The Contributor Summit will also be over two days, on Monday 1st and Thursday 4th October, from 9:30am to 4pm (time subject to change).

### This is your event

Ansible succeeds because of its community, and this contributor summit is for you. If you have any topics to discuss, large or small, please be sure to post those topics on the etherpad. For topics that other had added please vote by adding +1

https://etherpad.openstack.org/p/ansible-summit-october-2018 

Please see https://groups.google.com/forum/#!topic/ansible-devel/ivrpVbLya8g for further info

### Attending in person

We realize that not everybody can attend in person, which is why we’ll again be arranging a video conference and a meeting time on IRC in #ansible-meeting to encourage remote participation. This has worked very well for the past Contributor Summits. We’ll be sending out an email with the information for remote participation about a week before the Contributor Summit. 

If you want to attend in-person please sign up at: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 

After signing up you'll receive an email from Eventbrite with a discount code for AnsibleFest Austin. 


### Attending remotely

Please add your name at the bottom of this etherpad: https://etherpad.openstack.org/p/ansible-summit-october-2018 

### Call to action

1) Add ideas to https://etherpad.openstack.org/p/ansible-summit-october-2018 
2) Attending in person: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 then use discount code to sign up to AnsibleFest
3) Attending in person OR virtually: Add your name to the end of https://etherpad.openstack.org/p/ansible-summit-october-2018 
4) Happy automating!

### Questions?
Thanks for all of your contributions to Ansible, and we hope to see you in Austin! And if you have any questions at all, please let us know. 

Speak to `gundalow` on Freenode, or anyone else in `#ansible-devel`

**Comment by mattclay** [comment]
https://github.com/ansible/ansible/pull/45444 - Be careful about resource costs when working with integration tests.

**Comment by gundalow** [comment]
Anyone in here used Molecule? There is an Azure driver PR https://github.com/metacloud/molecule/pull/1491 which maybe of interest.

As you may know [Ansible is adopting Molecule](https://groups.google.com/forum/#!topic/ansible-project/ehrb6AEptzA)

**Comment by mattclay** [comment]
Two new [Broken Azure Tests](https://github.com/ansible/ansible/projects/22).

**Comment by mattclay** [comment]
Reminder to check for the `stale_ci` label before merging PRs. Ideally use the `rebuild_merge` bot command instead of manually merging (the bot checks for `stale_ci` and rebuilds if needed).

Two PRs were merged which were marked `stale_ci` and both had CI failures:

https://github.com/ansible/ansible/pull/46796
https://github.com/ansible/ansible/pull/47045

**Comment by yungezz** [comment]
@mattclay  sorry for the CI broken. and thanks for helping fixing the author issue. We'll keep in mind on stable_ci label before merging PRs. didn't aware of it..

**Comment by mattclay** [comment]
New [Broken Azure Tests](https://github.com/ansible/ansible/projects/22).

**Comment by mattclay** [comment]
Discuss the correct way to rename modules. See: https://github.com/ansible/ansible/pull/57395#pullrequestreview-246913075

**Comment by gundalow** [comment]
# Ansible Fest: Contributors Summit 

Just a reminder that Contributors Summit is happening on Monday 23rd September and will be streamed online and you can make your voice heard via IRC.

[When is this in my timezone?](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ansible+Contributor+Summit&iso=20190923T1250&p1=1440&ah=8&am=10)

To see what we plan to discuss see the [top level Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
From there you can see the various breakout sessions.
A lot of the morning session will be around Collections

## Call to Action!

Even if you can only make a small part of the day, or maybe can't attend at all, there are still ways take part:

* Add your thoughts, ideas and questions to the [Breakout Agenda](https://etherpad.openstack.org/p/ansible-summit-atlanta-2019)
* Vote on what you'd like to be discussed (ie add `+yourname`)


## Background Reading

A large part of Monday Morning will be around "Ansible Collections", to get up to speed on what the current thoughts are, the following links will help you:

[Blog: Thoughts on restructuring the Ansible Project](https://www.ansible.com/blog/thoughts-on-restructuring-the-ansible-project)
[Blog: The future of Ansible Content Delivery](https://www.ansible.com/blog/the-future-of-ansible-content-delivery)
[Webinar: Collections and the future of how Ansible Content is handled](https://www.ansible.com/resources/webinars-training/collections-future-of-how-ansible-content-is-handled)
[Docs: Collections Tech Preview Guide](https://docs.ansible.com/ansible/devel/dev_guide/collections_tech_preview.html)

# NEW: Community Central (drop in space)

At AnsibleFest 2019 we are excited to launch Community Central, a gathering place and information hub for Ansible contributors. This takes place 10-3pm each day at AnsibeFest.

Community Central builds on the success of Ask an Expert, with a focus on contributors rather than users.

Community Central will host informal talks and coding sessions on the main conference days. Members of the Ansible Engineering team and the various Ansible Working Groups will be there.

It's a great place to discover how you can contribute to Ansible, meet other contributors, or polish your latest Ansible pull request. If you already contribute to Ansible, or would like to find out how to get involved, this is the place for you!

Feel free to come along and say hello, or even bring your laptop and we can help you through any part of the contributor or development process. Keep an eye on the Agenda Builder to see what's happening.

# Questions?

Any questions, feel free to ping me

Email: gundalow@redhat.com
Freenode: `#ansible-community`
Matrix: [ansible-community](https://matrix.to/#/#freenode_#ansible-community:matrix.org)
GitHub: @gundalow 
Twitter: @the_gundalow

**Comment by gundalow** [comment]
## Ansible Contributors Summit EUROPE

## What

Ansible Contributor Summit is a one day event especially for community contributors to meet with each other, as well as Ansible development teams (Core, AWX/Tower, Galaxy) in person, to discuss important issues in the community and help shape the future of Ansible. For those unable to make it to Gothenburg, we welcome you to join virtually for part/all of the day. Online participation and streaming details to follow closer to the summit.

## When
* Contributors Summit: Sunday, 29th March
* Ansible Hackathon: Monday 30th March
* [FOSS-North](https://foss-north.se/2020/): 30 & 31st March

## How

* If you plan to attend **in person**, please register on [Eventbrite](https://www.eventbrite.com/e/ansible-contributor-summit-eu-registration-92039844653)
* If you plan to attend the hackathon or any of FOSS-North please [register](https://foss-north.se/2020/)
* If you plan to attend virtually details will be added to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020) the day before

## Agenda

* Please add suggested topics to the [Etherpad](https://etherpad.openstack.org/p/ansible-contributor-summit-gothenburg-2020)
For more info please see the [announcement](https://groups.google.com/forum/#!topic/ansible-devel/o6xnI9g8QqM).
