### ISSUE TITLE
Open Call for Community Events in Berlin - June 2018

### ISSUE THREAD

**Issue by lhawthorn** [ansible/community#307]
The [FOSS Backstage conference](
https://foss-backstage.de/
) welcomes setting up "satellite events" piggybacking on their conference, taking place 13-14 June 2018. The offer is also open for [Berlin Buzzwords](https://berlinbuzzwords.de/), the prior week, 10-12 June.

If you are in or around Berlin and would be interested in setting up a satellite event, please get in touch. I would be happy to tell you if your proposed idea would be welcome to the audience and to get you in touch with the right people to get things set up. Best way to reach me is via email on my work address, lhawthor @ company name dot com.

**Comment by robynbergeron** [comment]
Hi @lhawthorn -- 

Thanks for submitting this. Apologies that we didn't have the bandwidth to broadly advertise this. On the list of things we strive to do once we have a bit more headcount and/or organized community focus on awareness of events to alert people to and/or focus on. 

I did label this as an outreach item so that in the future we can at least find it by label, when we get to the point of assessing how to provide awareness of events where we have opportunities of this sort 

In the meantime: Closing this, since both of these lovely events in June have passed. You are of course encouraged to share other things in the future, esp. since it provides us a reminder about all the things we're missing out on :) And your notification is appreciated -- I'm just sorry that we weren't able to dedicate time to this particular effort at this moment in time. 

(ALSO HUGS TO YOU, miss you lh!)
