### ISSUE TITLE
Public Ansible Project Meeting Agenda - August 2018

### ISSUE THREAD

**Issue by bcoca** [ansible/community#329]
Please leave a comment regarding any agenda item you wish to discuss. If you don't show up for the meeting, your item will be skipped.

If your IRC nick is different from your Github username, leave that as well.

See https://github.com/ansible/community/blob/master/meetings/README.md for the schedule

Once an item has been addressed it should get strike-though strike-though

When creating new agenda ensure core and meeting_agenda labels are set

**Comment by gundalow** [comment]
## Ansible Contributor Summit 6 (Part of AnsibleFest 2018 Austin, Texas)

As part of http://www.ansible.com/ansiblefest

* AnsibleFest Austin will be on both Tuesday 2nd and Wednesday 3rd October 2018
* The Contributor Summit will also be over two days, on Monday 1st and Thursday 4th October, from 9:30am to 4pm (time subject to change).

### This is your event

Ansible succeeds because of its community, and this contributor summit is for you. If you have any topics to discuss, large or small, please be sure to post those topics on the etherpad. For topics that other had added please vote by adding +1

https://etherpad.openstack.org/p/ansible-summit-october-2018 

Please see https://groups.google.com/forum/#!topic/ansible-devel/ivrpVbLya8g for further info

### Attending in person

We realize that not everybody can attend in person, which is why we’ll again be arranging a video conference and a meeting time on IRC in #ansible-meeting to encourage remote participation. This has worked very well for the past Contributor Summits. We’ll be sending out an email with the information for remote participation about a week before the Contributor Summit. 

If you want to attend in-person please sign up at: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 

After signing up you'll receive an email from Eventbrite with a discount code for AnsibleFest Austin. 


### Attending remotely

Please add your name at the bottom of this etherpad: https://etherpad.openstack.org/p/ansible-summit-october-2018 

### Call to action

1) Add ideas to https://etherpad.openstack.org/p/ansible-summit-october-2018 
2) Attending in person: https://www.eventbrite.com/e/ansible-contributor-conference-austin-2018-tickets-48557063484 then use discount code to sign up to AnsibleFest
3) Attending in person OR virtually: Add your name to the end of https://etherpad.openstack.org/p/ansible-summit-october-2018 
4) Happy automating!

### Questions?
Thanks for all of your contributions to Ansible, and we hope to see you in Austin! And if you have any questions at all, please let us know. 

Speak to `gundalow` on Freenode, or anyone else in `#ansible-devel`

**Comment by agowa338** [comment]
I'd like to put my pull request #43689 onto the list.

**Comment by bcoca** [comment]
https://github.com/ansible/proposals/issues/39

**Comment by sivel** [comment]
For discussion on August 14:

Do we continue with deprecating `with_` now?  If not why? What do we need to get that on track?

Are we unhappy with the UI of transitioning to `loop` (too much jinja2?)?  Who is going to make a proposal to get `loop` to where we need it.

**Comment by abadger** [comment]
file will gain the ability to set a specific timestamp on the files it modifies: https://github.com/ansible/ansible/pull/43230   shall we change the touch state so that it is idempotent by defaulting to timestamp=same (meaning, do not change the timestamp) for its action.

This would bring it inline with all the other states in file and make it idempotent but would be a backwards compatible break.

**Comment by bcoca** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-09/ansible_core_irc_meeting.2018-08-09-15.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-08-09/ansible_core_irc_meeting.2018-08-09-15.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-09/ansible_core_irc_meeting.2018-08-09-15.00.log.html

**Comment by sivel** [comment]
Swap default for `INVALID_TASK_ATTRIBUTE_FAILED` added in https://github.com/ansible/ansible/pull/42480 to be `True`.  This would cause users to have an immediate failure on playbook that may have been "working".

**Comment by bcoca** [comment]
https://github.com/ansible/community/issues/329 <= choose a name and run with it

current bikeshed: incumbent (gives preference to currently executing hosts)

**Comment by maxamillion** [comment]
Request for further/final comments/review on the Yum and DNF refactor before merge. Also need to request an exception be granted for making a GPLv3 module_util as in some cases we are unable to get permission to re-license the derivative work. https://github.com/ansible/ansible/pull/43621

**Comment by gundalow** [comment]
Contributors Summit https://etherpad.openstack.org/p/ansible-summit-october-2018
* Add ideas/topics
* If attending in person please sign up

**Comment by bcoca** [comment]
Meeting ended Tue Aug 14 20:27:05 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-14/ansible_core_irc_public_meeting.2018-08-14-19.00.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-08-14/ansible_core_irc_public_meeting.2018-08-14-19.00.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-14/ansible_core_irc_public_meeting.2018-08-14-19.00.log.html

**Comment by bcoca** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-16/public_core_irc_meeting.2018-08-16-15.03.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-08-16/public_core_irc_meeting.2018-08-16-15.03.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-16/public_core_irc_meeting.2018-08-16-15.03.log.html

**Comment by pilou-** [comment]
* [new module openssl_pkcs12](ansible/ansible#27320)
   * author: @gdelpierre (IRC: `Llew`)
   * approved by Spredzy (as a crypto namespace maintainer) and me :)
   *  integration tests provided !

* [Share the implementation of hashing for both vars_prompt and password_hash](ansible/ansible/pull/21215)
  * author: @mfuchs
  * approved by dharmabumstead (as doc maintainer) and me :)
  * unit tests provided !

* [gather_facts improvements](ansible/ansible#44008)
  * author: myself
  * approved by bcoca

**Comment by jwitko** [comment]
- new module docker_swarm_service](https://github.com/ansible/ansible/pull/19229)
-- author: @dariko @jwitko

**Comment by bcoca** [comment]
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-23/ansible_core_public_irc_meeting.2018-08-23-14.59.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-08-23/ansible_core_public_irc_meeting.2018-08-23-14.59.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-23/ansible_core_public_irc_meeting.2018-08-23-14.59.log.html

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/42163

**Comment by sieben** [comment]
I would like to have reviews on: https://github.com/ansible/ansible/pull/44377

**Comment by sieben** [comment]
https://github.com/ansible/ansible/pull/44122 https://github.com/ansible/ansible/pull/44384 https://github.com/ansible/ansible/pull/44342

**Comment by bcoca** [comment]
https://github.com/ansible/proposals/issues/57

**Comment by dagwieers** [comment]
ansible/ansible#37645

**Comment by bcoca** [comment]
Meeting ended Tue Aug 28 20:03:05 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-28/ansible_core_public_irc_meeting.2018-08-28-19.02.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-08-28/ansible_core_public_irc_meeting.2018-08-28-19.02.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-28/ansible_core_public_irc_meeting.2018-08-28-19.02.log.html

**Comment by bcoca** [comment]
Meeting ended Thu Aug 30 16:04:10 2018 UTC. Information about MeetBot at http://wiki.debian.org/MeetBot .
Minutes: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-30/ansible_core_irc_public_meeting.2018-08-30-14.59.html
Minutes (text): https://meetbot.fedoraproject.org/ansible-meeting/2018-08-30/ansible_core_irc_public_meeting.2018-08-30-14.59.txt
Log: https://meetbot.fedoraproject.org/ansible-meeting/2018-08-30/ansible_core_irc_public_meeting.2018-08-30-14.59.log.html
