### ISSUE TITLE
Define old PR work flow

### ISSUE THREAD

**Issue by gundalow** [ansible/community#356]
When should old PRs be closed, esp the ones waiting on contributor

**Comment by dagwieers** [comment]
Old PR's may still be valuable, so I would consider them as feature requests or bug reports if they become stale. Maybe we should turn them into `needs_contributor` so that it becomes clear to the existing contributor we want to go forward, if necessary without him.

Obviously if there's no value in pursuing the PR it could be closed, but auto-closing is not something I would like to see happen. So maybe that `needs_contributor` could be the flag to avoid auto-closing ? Especially if there's a larger outside interest in that specific PR.
