### ISSUE TITLE
Paris Meetup Organisers

### ISSUE THREAD

**Issue by gundalow** [ansible/community#364]
Form pilou-

> Hi ! There has been no Ansible-Paris meetup since 10 months and the organizer (Aurélien) seems unresponsive (last unanswered message sent via meetup website: April 2018). Two weeks ago, participants of the sprint misc and I organized in Paris have expressed their willingness to organize the next Ansible-Paris meetup. Is that possible to add a new Ansible-Paris meetup organizer ? Could you do that ?

>  https://www.meetup.com/Ansible-Paris/members/235715310/ https://www.meetup.com/Ansible-Paris/members/196664425/ (both if possible or at least the first)

**Comment by aurelienmaury** [comment]
Hi,
I have been pinged on twitter by Rémy Rey and informed of this thread. I am the current in-charge manager of the Ansible Paris Meetup. Even after looking closely, I have no meetup message dating from last April. Don't know why...

Anyway, Rémy and Pilou, are now both co-orga. We discussed that I could stay in-charge orga so that I continue to pay the bill for the Meetup Account. We also discussed that we (me and my company) would be more than happy to welcome the next instance at our offices, if they like to.

Also, from a personal point of view, I'm glad that someone raised a hand to inject energy in Ansible Paris. If that escalation needs more actions, please tell me.

**Comment by gundalow** [comment]
@aurelienmaury thank you for the update. Having a people to help run the Meetups is key. For a while I was running the London meetup by myself, it's takes a lot of energy. 

Please let us know if there is anything we can do to help. 

@pilou- anything left to do here?

**Comment by pilou-** [comment]
It's fine, thank you!

**Comment by gundalow** [comment]
Thank you all. I'll close this issue.

Please shout out if we can help with anything. 

May I suggest that you all subscribe to https://groups.google.com/forum/#!forum/ansible-outreach

Also on Freenode IRC we have `#ansible-community`

**Comment by gundalow** [comment]
All, you may find it useful to sign up to the `outreach` email list (low traffic) https://groups.google.com/forum/#!forum/ansible-outreach
