### ISSUE TITLE
Discourse? 

### ISSUE THREAD

**Issue by gundalow** [ansible/community#396]
From @webknjaz 
> just wanted to bring this to your attention. Lots of communities seem to be moving to [discourse](https://github.com/discourse/discourse).
>
> Examples:
>- https://discuss.python.org/
>- https://travis-ci.community/
>- https://github.community/
>- https://platform.github.community/
>- https://education.github.community/
>- https://discourse.mailinabox.email/
>- https://talk.vespene.io/
>
>Also, while having discussions @ PyPA Sprint a week ago one of the cpython maintainers explained to me that one of the reasons for setting it up was that younger people are less likely to be attracted to "old-school" IRC and mailing lists. Platforms like this also encourage more active engagement.
>
>Do you think this is something we should take into account? Can we benefit from building a community on such a platform?

**Comment by tuxerrante** [comment]
Hi,
I'm really new to Ansible and I'm waiting a [very easy issue](https://github.com/ansible/ansible/issues?q=is%3Aopen+is%3Aissue+label%3Aeasyfix) to get my feet wet (suggestions?). 

After reading first doc chapters I came to the IRC channel, as first impression I found it very dispersive and it is hard to keep track of the conversation during hours or days. In my opinion is harder, too, starting to talk for new users while more experienced ones are writing in the public chat.

Discourse instead is more Reddit style and it could be very helpful to track more important messages, all the new features from a subscribed topic with the addition of the trust system which will be very useful for you.

**Comment by mscherer** [comment]
The problem with discourse is that suddenly, folks who are active on multiple community (like I do) will  have X instances to follow, and that is far from being optimal (unlike irc where I can do all from 1 single place, so I can bundle the time I spend my attention ). 

I also think that the addictive nature of forum would distract people (since you have to check actively the answer instead of having them pushed to you), so I suspect a uptick in discussion will mean we are stealing attention from somewhere else.

**Comment by webknjaz** [comment]
@mscherer please consider the fact that modern young people are less used to IRC. We need to look out to be friendly to everyone, not excluding certain groups.

Regarding:
> [...] will have X instances to follow [...]
> [...] since you have to check actively [...]

I'm myself registered on multiple discourse instances. So my takeaways are:
1) don't do manual checks, it's not needed. there's a way to get browser and/or email notifications.
2) you can control what you're being notified about. you can "watch" a category, for example. you can be notified about replies to you personally etc.
3) the thing I like a lot is that there's no need to maintain a new login/password thing: there's plugins to easily integrate auth via github or other services.
4) on topic creation this thing actually tries to point to other similar topics automatically, so you don't waste time trying to manually find out whether anybody created one already, for example.
5) you can search across well-indexed content

**Comment by webknjaz** [comment]
Hey @tuxerrante,

Thanks for your feedback!

wrt the first issue, there's also https://github.com/ansible/ansible/labels/waiting_on_contributor, which are not necessarily easy, but there might be some among those. I'd say it all depends on your areas of interest and skill set :)

**Comment by mscherer** [comment]
@webknjaz I do not think there is a need to repeat the same point over and over, as the assumption regarding younger generation is already laid out in the initial comment, and I did read it fine the first time.

I also already know how Discourse work, as I was quite active on the Silverblue/Fedora one before deciding to switch back to regular Fedora (and stop using the platform, for reasons I can outline), and I did setup one instance as part of my job for others communities, so my feedback is based on my regular usage of it. 

And if the goal is to replace real time discussion, then you need notifications, and this get messy quickly. So saying "you can turn that off" is a wrong answer.

If the goal is to replace a ML (so asynchronous discussion), then the whole point about "people do not use IRC" is confusing and useless, because they are not the same. 

And if the goal is to replace nothing but just add one more options, then maybe there is no need to add yet another option and fragment the community between reddit, 3 or 4 irc channels, folks on slack and the 2 MLs. In the end, attention is a limited ressource.

But there is no such goals explained, because the premise start by suggesting tools, not problems, and this is often the wrong way to approach a problem. You do not start by the solution and then find why you want something.

So what are the issues to be solved ? (and not what are the issues that Discourse could solve, because this is just the same approach hidden under the pretence of doing things in the right way).

I think no one said "we do not have young people", because no one did a survey to verify it, no one defined younger generation, and I think "the community is too small" is not a problem we have. 

And just increasing engagement for the sake of increasing is chasing a metric without defining how this matter. Engagement is a euphemism for "stealing attention", and again, i think we do not have a need for a generic bigger community. 

For companies like Twitter and Facebook, or Github, where having users mean having money and a direct conversion pipeline, sure, there is a reason for them to "engage" more people. They do sometime engage in unethical manipulation for that, but at least, they have a direct justification, and dedicated team.

Or even for a project like Vespene, where there is no community, you want to grow and engage. 

I fail to see how that's a priority for us when we have already trouble to handle the amount of existing discussion and patches, and how investing time and money for either increase the problem or have a neutral effect is a good thing.

**Comment by samccann** [comment]
The Ansible Community Forum is alive! https://forum.ansible.com/
