### ISSUE TITLE
AIX community pinboard

### ISSUE THREAD

**Issue by dagwieers** [ansible/community#421]
[![Github aix issues](https://img.shields.io/github/issues/ansible/ansible/aix.svg?label=issues)](https://github.com/ansible/ansible/issues?q=is:open+is:issue+label:aix) [![Github aix PRs](https://img.shields.io/github/issues-pr/ansible/ansible/aix.svg?label=pull+requests)](https://github.com/ansible/ansible/issues?q=is:open+is:pr+label:aix) [![AIX pinboard](https://img.shields.io/github/issues/detail/last-update/ansible/community/421.svg?label=pinboard+update)](https://github.com/ansible/community/issues/421)

We could collectively benefit from forming a Working Group related to AIX integration. We have quite some contributors on Github and users on IRC that are interested in improving this integration.

So this *issue* is a wake-up call to potential interested parties (earlier and existing contributors to Ansible).  The benefits of having a Working Group is that members of the Working Group can:
- test, review and add *shipits* to existing AIX PRs
- work collectively on the AIX roadmap
- provide a single-point-of-contact for interested AIX contributors
- collaborate on [an AIX-specific Wiki](https://github.com/ansible/community/wiki/AIX)
- have a $team_aix in BOTMETA.yml for auto-notifying team members (ansible/ansible#50660)
- implement auto-labeling AIX issues and PRs (ansible/ansible#50660)

Since we don't have any AIX infrastructure for automated testing, collaborating on modules like this is important for the quality of the modules.

**Comment by dagwieers** [comment]
cc @marvin-sinister @kairoaraujo @flynn1973 @gforster @sdodsley @jokurz @inxonic @mscherer @nrwahl2 @mtkunkel @molekuul @adejoux @fallencliff @Yannig @kstrauser @bmanojlovic @henkwiedig @qvicksilver @MorrisA @zitterbacke @mplonka @madema
cc @samdoran @tmshn @kcberg

If you want to actively lead or are interested to be part of this Working Group, show your support in this ticket ! If we have a large enough group, we can start our own AIX Working Group.

I started labeling all the AIX related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:aix
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:aix

**Comment by dagwieers** [comment]
If you want to actively lead or are interested to be part of this Working Group, show your support in this ticket ! If we have a large enough group, we can start our own AIX Working Group.

I started labeling all the AIX related issues and PRs so we can more easily track them:
- https://github.com/ansible/ansible/pulls?q=is:pr+is:open+label:aix
- https://github.com/ansible/ansible/issues?q=is:issue+is:open+label:aix

PS If you no longer wanted to receive any messages from this pinboard, feel free to unsubscribe from this issue ticket.

**Comment by MorrisA** [comment]
While my current focus at work is Linux and Windows I would be interested in taking part as I have time. 
 Improved AIX support will be useful for me.  

There might be others from my work interested in helping, but they are now in a different team so I cannot speak for them.  I will however make them aware of this initiative.

**Comment by gforster** [comment]
I am interested in participating as I am able to.

**Comment by kairoaraujo** [comment]
I am very interested in that :)
All modules I have been contributing is related to AIX. I also have some unfinished modules for PowerHA/HAMCP, etc.

**Comment by dagwieers** [comment]
I created [a wiki page](https://github.com/ansible/community/wiki/AIX) and added [a $team_aix entry](https://github.com/ansible/ansible/pull/50660). Feel free to add ideas and todo items to the Wiki page or contact me if you need something. The first thing that is needed is reviewing the open PRs and issues to get those moving before the Ansible v2.8 freeze.

*PS More people are very welcome to the team.*

**Comment by dagwieers** [comment]
Now that we have an assembly of 6, should we hold a first meeting?

Agenda:
- Who wants to pull this initiative? *(My role will be supportive, I have no access to AIX currently)*
- Do we create a proper AIX Working Group, or have a Unix Working Group instead (i.e. Solaris, HP/UX, and possible BSD flavors)
- Do we want regular meetings to keep momentum?
- What actions do we take to get PRs merged and issues resolved?
- Any other topics to bring up?

**Comment by gforster** [comment]
Same here. Limited capacity, but will do all I can. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MorrisA** [comment]
I have access to AIX... But I also have to deal with my job as a priority.  This unfortunately is not a high priority for me.   I am hoping that I can persuade one of my colleagues who is more directly affected to join in.

**Comment by kairoaraujo** [comment]
Hi, until end of March I am a bit overloaded. Anyway count with me :)

I have an IBM p7, however it is down and I don’t have place to power on it. It could be used for tests as well. 
As soon as possible I want to contribute more.

**Comment by dagwieers** [comment]
@kairoaraujo The community freeze is scheduled for mid March, see https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_8.html So that would mean your modules would not be included in v2.8 :-/ I propose we review those modules ASAP, and hopefully you find the time to bring them into shape for merging before the deadline.

**Comment by molekuul** [comment]
Hi At this moment I do have access to AIX servers so I am able to test AIX ansible modules. As with everybody else, I 'm very busy with my job at my customer. however I want go get the flow running.

Kind regards,

Joris Weijters

**Comment by gforster** [comment]
Topic suggestion: a common testing framework for AIX (since we can’t use shippable)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dagwieers** [comment]
@gforster The common testing framework is the Ansible test framework (basically a set of playbooks in *test/integration/targets*). They will be unsupported by Shippable CI, but they give a common testing process for everyone that wants to test PRs or changes on their infrastructure.

https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

    ansible-test integration --allow-unsupported aix_.*

Integration tests normally perform idempotency and check-mode, and perform create, modify and delete operations.

PS We should try to create non-destructive integration tests. By default destructive integration tests are not run by ansible-test.

**Comment by marvin-sinister** [comment]
I'm a bit late, but i'm interested. Unfortunatelly I don't have access to AIX.

**Comment by mator** [comment]
adding myself

**Comment by dagwieers** [comment]
The **installp** modules has been merged into the devel branch. If you have an AIX environment, please test this module (and contact me to work on an integration test for this module).

**Comment by dagwieers** [comment]
So the amount of support here is amazing, and I think my role here is slowly fading to the background. I am happy to welcome @kairoaraujo as the AIX Lead in this Working Group. In the meantime we are still learning how these communities can help improve contributors and users. I started to write down [how I envision the different roles](https://github.com/ansible/community/wiki/Roles) in Working Groups.

There is room for more people taking up the Lead role, so if you think you have some extra cycles to spare to help grow this community, let me know.

[The Ansible v2.8 freeze is nearing](https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_8.html) and we have about a month to get as much as possible reviewed and fixed. Feel free to reach out to @kairoaraujo, @gundalow and me if you need any help. Let's make the upcoming release the best one for AIX ever :-)

**Comment by ramooncamacho** [comment]
I work with AIX and VIO Servers, and I use ansible to coordinate the environment, routines and self healing. I can create isolated aix servers for testing purposes, and would be pleased to help.

**Comment by kairoaraujo** [comment]
Thank you @ramooncamacho. I will tag you to PR that there is integration tests then you can test it :)

**Comment by dagwieers** [comment]
@ramooncamacho If you add yourself to the group on the Wiki page, I can add you to the $team in @ansibot so you get involved in issues/PRs. We have 7 open issues that needs someone to verify if they are valid, and we have 9 open PRs which require review and testing.

I wrote a small page on [Reviewing issues and PRs](https://github.com/ansible/community/wiki/Reviewing) on the Wiki. Feedback welcome.

**Comment by ramooncamacho** [comment]
I've added myself in the Wiki Page and configured the environment to start reviewing the PRs.

**Comment by d-little** [comment]
I've added myself to the Wiki, and am still exploring the Ansible universe.  

One question I have though WRT roles/collections(eventually);  Do we want to expand commonly used community roles that do a good job of supporting a couple of tasks in Linux and add AIX support, or do we want to create entirely new roles/collections dedicated to AIX?

Case in point, I've made some changes to [this great Samba role](https://github.com/bertvv/ansible-role-samba) to include some support for AIX, [currently here](https://github.com/d-little/ansible-role-samba).  

Do we, as an Ansible AIX Community, want to keep our roles seperate, or included with the greater-Linux community?  Some roles will obviously be separate, NIM and VIOS for example, but many features are shared between Linux and AIX now, like Samba, User/Group management, etc.  

Thoughts?  Also, is this the right place for these sorts of thoughts, or do we we have another better discussion forum?

**Comment by franciscolozada** [comment]
Hi Guys,

I'm not sure if this is the right place to post this question... I'm a aix admin. I took ansible class do07 and all work was done on linux... It seems very straight forward on linux, however when I installed ansible on AIX, somehow I have to run it with sudo in order to work. I did  rpm -ql on ansible and changed permissions to 755 to all files related, yet I still have permissions issues. Please, advice:
flozada-a-xnv1491501556:/home/flozada> ansible --version
Unhandled error:
 Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 487, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 439, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 93, in ensure_type
    value = tempfile.mkdtemp(prefix=prefix, dir=value)
  File "/opt/freeware/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-24444930YHqKH_'

flozada-a-xnv1491501556:/home/flozada> ansible nim1p1x  -i x -m ping
Unhandled error:
 Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 487, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 439, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 93, in ensure_type
    value = tempfile.mkdtemp(prefix=prefix, dir=value)
  File "/opt/freeware/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-51775886XEFDO'


Traceback (most recent call last):
  File "/usr/bin/ansible", line 67, in <module>
    import ansible.constants as C
  File "/opt/freeware/lib/python2.7/site-packages/ansible/constants.py", line 184, in <module>
    config = ConfigManager()
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 243, in __init__
    self.update_config_data()
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 499, in update_config_data
    raise AnsibleError("Invalid settings supplied for %s: %s\n%s" % (config, to_native(e), traceback.format_exc()))
ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-51775886XEFDO'
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 487, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 439, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 93, in ensure_type
    value = tempfile.mkdtemp(prefix=prefix, dir=value)
  File "/opt/freeware/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-51775886XEFDO'

flozada-a-xnv1491501556:/home/flozada> sudo ansible --version
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/flozada/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/freeware/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Sep 28 2018, 03:58:41) [GCC 6.3.0]

**Comment by flynn1973** [comment]
For aix open source software related questions go here -> https://www.ibm.com/developerworks/community/forums/html/forum?id=2eb0f36d-9534-471b-8b27-c21e6c5b9b2b


________________________________­­­
Christian Tremel
IT-Services der Sozialversicherung GmbH

Rechenzentrum
AIX Systemadministrator
Gruberstraße 77
A – 4021 Linz
T: +43 (0)50124 844 1266
M: +43 (0)664 88661266
christian.tremel@itsv.at<mailto:christian.tremel@itsv.at>
www.itsv.at<http://www.itsv.at>

[https://plattform.sozvers.at/Lists/Schlagzeilen/Attachments/493/CIS-Logo-Signatur.png]


Von: franciscolozada [mailto:notifications@github.com]
Gesendet: Donnerstag, 05. September 2019 19:43
An: ansible/community <community@noreply.github.com>
Cc: Tremel Christian <Christian.Tremel@itsv.at>; Mention <mention@noreply.github.com>
Betreff: Re: [ansible/community] AIX community pinboard (#421)


Hi Guys,

I'm not sure if this is the right place to post this question... I'm a aix admin. I took ansible class do07 and all work was done on linux... It seems very straight forward on linux, however when I installed ansible on AIX, somehow I have to run it with sudo in order to work. I did rpm -ql on ansible and changed permissions to 755 to all files related, yet I still have permissions issues. Please, advice:
flozada-a-xnv1491501556:/home/flozada> ansible --version
Unhandled error:
Traceback (most recent call last):
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 487, in update_config_data
value, origin = self.get_config_value_and_origin(config, configfile)
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 439, in get_config_value_and_origin
value = ensure_type(value, defs[config].get('type'), origin=origin)
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 93, in ensure_type
value = tempfile.mkdtemp(prefix=prefix, dir=value)
File "/opt/freeware/lib/python2.7/tempfile.py", line 339, in mkdtemp
os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-24444930YHqKH'

flozada-a-xnv1491501556:/home/flozada> ansible nim1p1x -i x -m ping
Unhandled error:
Traceback (most recent call last):
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 487, in update_config_data
value, origin = self.get_config_value_and_origin(config, configfile)
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 439, in get_config_value_and_origin
value = ensure_type(value, defs[config].get('type'), origin=origin)
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 93, in ensure_type
value = tempfile.mkdtemp(prefix=prefix, dir=value)
File "/opt/freeware/lib/python2.7/tempfile.py", line 339, in mkdtemp
_os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-51775886XEFDO'

Traceback (most recent call last):
File "/usr/bin/ansible", line 67, in
import ansible.constants as C
File "/opt/freeware/lib/python2.7/site-packages/ansible/constants.py", line 184, in
config = ConfigManager()
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 243, in init
self.update_config_data()
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 499, in update_config_data
raise AnsibleError("Invalid settings supplied for %s: %s\n%s" % (config, to_native(e), traceback.format_exc()))
ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-51775886XEFDO'
Traceback (most recent call last):
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 487, in update_config_data
value, origin = self.get_config_value_and_origin(config, configfile)
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 439, in get_config_value_and_origin
value = ensure_type(value, defs[config].get('type'), origin=origin)
File "/opt/freeware/lib/python2.7/site-packages/ansible/config/manager.py", line 93, in ensure_type
value = tempfile.mkdtemp(prefix=prefix, dir=value)
File "/opt/freeware/lib/python2.7/tempfile.py", line 339, in mkdtemp
_os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/home/flozada/.ansible/tmp/ansible-local-51775886XEFDO'

flozada-a-xnv1491501556:/home/flozada> sudo ansible --version
ansible 2.7.0
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/flozada/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /opt/freeware/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.15 (default, Sep 28 2018, 03:58:41) [GCC 6.3.0]

**Comment by flynn1973** [comment]
guys, quick question. i'm stuck adding new aix facts to core.
see stackoverflow question -> https://stackoverflow.com/questions/58198289/ansible-facts-gathering-mech
please, can someone take a look, already asked on irc but no luck.
