### ISSUE TITLE
Look into Reno (release notes generator), maybe make a proposal?

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#61]
I was enlightened this weekend regarding the existence of a tool called Reno, which appears to make it super easy / sane to create release notes for a project. It was created by the nice folks in the land of OpenStack. I have spoken to a few people who find it to be quite handy and awesome and easy.

In a nutshell: Reno allows you to include a simple, yaml-formatted file as part of a commit of something that is "release notes-worthy", and then bundles up all the various release notes for a release into one tidy document. 

Since it looks awesome and useful, I was thinking about creating a proposal, but figured maybe I'd just add this as a note for discussion at our next community meeting and see what we thought. Things I'm specifically wondering are: (a) does this seem like it would be confusing / add bureaucracy ("how do I know if something is release note worthy or not?"), and (b) to even get this to being a proposal, I'd need to know how to, um, implement it or at least outline the plan, and thus I'm not quite sure I'm the most appropriate person to make such a proposal.

Anyway, some background!
- [Reno Documentation](http://docs.openstack.org/developer/reno/)
- [Usage](http://docs.openstack.org/developer/reno/usage.html)
- [In PyPI](https://pypi.python.org/pypi/reno)

Nice things:
- It's Python!
- Notes are written in yaml! I think we know a thing or two about that. 
- Uses Sphinx! Which I think we also use for our docs. 

Things I don't know:
- Dependencies. Some stuff is listed in [PyPI](https://pypi.python.org/pypi/reno), but then there's also Sphinx, and more generally "other dependencies of our release process" that I don't know. (Maybe @emonty, the kind human who enlightened me as to the existence of this, knows if this is a terribly hard thing or a terribly easy thing to set up? And not sure if / how / if we'd want to do it across repos (ansible, modules-core, and modules-extras)?
- How to make it all happen, basically. :smiley: 

Why this is cool:
- Lots of things are possibly release-note worthy, but they're not always remembered by the time a release rolls around. 
- Inclusion happens when your PR for the thing being implemented / fixed / reverted happens, and thus you don't have to "make a note of it for later" or put it on your todo list. Similarly, if a PR is submitted that others feel is release-note worthy but doesn't have one, they can request for that to be done at that time and not have to figure out how to make that happen after the fact. 
- Awesome new work gets highlighted!
- Ensures that the release notes are created in a way that is as collaborative as the release itself!
- More reasons why this is cool are captured in the form of the [requirements for Reno when it was created.](http://docs.openstack.org/developer/reno/design.html)

How it works:

If you're doing a pull request for something that might warrant something in the release notes, such as a:
- feature
- deprecation
- fixed security issue
- fixed critical issue
- etc.

then you would...
- Create a simple YAML file describing what category it would go under ("features," "deprecations," etc.)
- When you make the commit implementing / fixing / whatever, include the file as part of the commit (in /releasenotes/notes). 
- And: Since it's tied to the same commit ID, if it gets reverted, isn't merged, etc. then you don't have to also remember to go to undo the release note. Bonus: if something is backported, release notes will follow as well!

As they say...

Sometimes an example is nice. 
- [This file](https://review.openstack.org/#/c/288715/22/releasenotes/notes/domain_operations_name_or_id-baba4cac5b67234d.yaml) was part of a commit in the Shade project implementing a new feature. (Yay, we :heart: Shade.) The content of the file looks like this:

```

---
features:
  - Added name_or_id parameter to domain operations, allowing
    an admin to update/delete/get by domain name.
```
- Upon the next release of Shade, the release notes were automatically generated, and this was automatically added to the "features" section and you can see how it looks [here](http://docs.openstack.org/infra/shade/releasenotes.html#id1). (note: yes, it was the only note in the release notes for that release, but if there has been more, then they would be aggregated into this as well)

**Comment by gregdek** [comment]
We will have a new hire at some point who is in charge of Ansible core documentation; this should perhaps live on that person's plate. Putting on Jason's plate for now.

**Comment by docschick** [comment]
please add dharmabumstead to this :)

**Comment by gregdek** [comment]
@dharmabumstead consider yourself pinged.

**Comment by abadger** [comment]
@jimi-c took a look at this last night and thought it was too heavy-weight.  I took a look at it this morning and didn't agree about it being heavy but there were some assumptions that make it not fit in with us well:

Once setup, the difference in workflow is very small to me.  before we'd do:
```
vim CHANGELOG.md
git commit -a
```

With reno we'd do:
```
reno new notable-change 
vim releasenotes/notes/notable-change*.yml
git commit -a
```

So just one extra step.  Editing the yaml file does involve deleting some sections that we don't need for the change.  On the other hand, you don't have to search through the changelog to figure out which section a change should be written to.  So it's probably only takes a tiny bit more time.

The assumptions that don't work well:
* reno determines what release notes go in which release based on when the branches diverge.  Since we work in devel and then backport via cherry-pick, it won't detect that some fix went into 2.1.2 first and so doesn't need to be noted in 2.2.0.

  This also means we need to run the report command for each branch we have notes in: reno report . --branch stable-2.2 ; reno report . --branch stable-2.3 ; etc
and if we want html rel notes, the page will have a separate .. release-notes::\n  :branch: BRANCHNAME for each of those as well.

* There's no way to permanently configure the directory where the relnotes live.  So you need to give it as a command line option via --rel-notes-dir if it's not in TOPLEVEL/releasenotes/  (could make a shell alias for this, though).  reno probably needs to look for a config file in the TOPLEVEL or a config file in the user's home that can map repositories to --rel-notes-dir.

**Comment by dharmabumstead** [comment]
I agree with @jimi-c. As I mentioned on the Slack channel previously, I think there's way too much overhead involved from the dev team to make this worthwhile. My experience has shown that only certain parts of the release notes process can be automated successfully; it's best done as a collaboration between the docs team and the dev team.

Here's the structure I used for release notes at Eucalyptus:

https://docs.hpcloud.com/eucalyptus/4.3.0/#release-notes/4.2.1/4.2.1_index.html

The 'resolved issues' section is the only section that is completely automated (it's generated from JIRA reports). 

The 'known issues' section is based *mostly* on JIRA tickets with the 'known issues' flag, partly from JIRA queries for release bugs that didn't get fixed, and from specific callouts of unresolved bugs that are sent to the docs team prior to release.

**Comment by gregdek** [comment]
Closing, clearly won't be implemented
