### ISSUE TITLE
how to create a new galaxy namespace for official alibaba cloud 

### ISSUE THREAD

**Issue by xiaozhu36** [ansible/community#664]
Hi team,

I am alibaba cloud engineer and I am in charge of alibaba cloud plugins for ansible. Now, the plugins has been migrated to https://github.com/alibaba/alibaba.alicloud, but there is no official collection in the https://galaxy.ansible.com/. I want to publish a new official alibaba.alicloud collection to the galaxy, but I happened an error when I publishing it:
```
Publishing collection artifact '/Users/heguimin/Projects/python/alibaba/alibaba.alicloud/alibaba-alicloud-1.0.0.tar.gz' to default https://galaxy.ansible.com/api/
ERROR! Error when publishing collection to default (https://galaxy.ansible.com/api/) (HTTP Code: 400, Message: Namespace "alibaba" does not exist. Code: invalid)
``` 
Is there any idea for adding a new namespace `alibaba`?

**Comment by felixfontein** [comment]
CC @Andersson007 @Spredzy

**Comment by Andersson007** [comment]
@xiaozhu36 @felixfontein hi, I'll ping folks internally

**Comment by Andersson007** [comment]
@xiaozhu36 please submit a namespace request as described in the [Collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#collection-naming).

I would also highly recommend you
- Subscribe to the [news-for-maintainers](https://github.com/ansible-collections/[news-for-maintainers](https://github.com/ansible-collections/news-for-maintainers)) repo and track announcements there. The ansible-core guys publish changes related to CI (and not only). So if you later set up testing, you'll be informed in advance about the changes. Otherwise, your CI will get red one day in PRs for unclear reasons.
- Optionally but highly recommended, subscribe to [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn).
- We have the [Maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst). Might be useful to take a look.
- If one day you want to see the collection to the ansible community package, I would recommend to take a look at the [Collection checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md) (it's a short version of the [Collection requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst)). Taking it in consideration at the development stage will potentially make the inclusion process easier for maintainers and reviewers.
- Share the above with future maintainers.

I'll close the issue, If there are any questions, feel free to ask.
Thanks!

**Comment by xiaozhu36** [comment]
@Andersson007 Thanks for your help and I have submitted the PR: https://github.com/ansible/galaxy/issues/2998
