### ISSUE TITLE
SLA for shipit

### ISSUE THREAD

**Issue by gregdek** [ansible/community#80]
Once a PR reaches "shipit", we should have an SLA for how long it takes for that PR is either merged or returned to needs_revision with comments. A week would be nice. Two weeks would be tolerable. More than two weeks is probably bad.

**Comment by ryansb** [comment]
Either works for me, but given the current state of things maybe 2 weeks is a good target to start with.

**Comment by gundalow** [comment]
Is there any way of tracking/graphing this?

It would be great to graph this and watch it improve over time

**Comment by gundalow** [comment]
Where "shipit" means the shipit label as assigned by the Bot or by a person

**Comment by abadger** [comment]
We talked about this this meeting without @jimi-c or @bcoca's presence.  We seemed to lean towards a two-week until automerge for PRs to existing modules in extras being fine (abadger, alikins, gundalow, jtanner, nitzmahone were +1,   sivel and ryansb abstained.  No dissenters).

We would like jimi-c and bcoca to object if they have issues with this proposal (I've pinged them so they can weigh in this week or let silence be consent ;-), otherwise that scope is fine.

We didn't come to a consensus on applying the same thing to other things (new modules, extras, etc).  @gregdek could you or robyn prioritize what would aspects of the expanded problem need to be addressed now so we can concentrate on those subsets for the next discussion?

**Comment by bcoca** [comment]
I would 'auto close' vs 'auto merge' as shipit should be dealt with daily during triage, having one stay open for 2 weeks means people really don't want to merge (but they should really say so).

**Comment by abadger** [comment]
We can't auto-close without disheartening the community.  1 person took the time to write it.  2 people took the time to review and approve it.  We can't discard their work without explaining what the shortcomings are so that they can improve for next time.

**Comment by bcoca** [comment]
It puts more pressure on reviewing in timely manner to not aggravate the community.

**Comment by abadger** [comment]
There's not a direct downside for us, though... the negative impact hits the community first.  Automerge puts pressure on us to explain why we don't want something if there's a problem with it.

**Comment by bcoca** [comment]
upset community will poke at us soon on an autoclose, automerge favors people ignoring the issue, letting it be merged and a long time later having to deal with the consequence.

Setting the default to the 'comfortable' setting promotes laziness, putting it on the 'pain' setting promotes proactive actions.

**Comment by ryansb** [comment]
I think if it's going to be auto-close, the time should probably be boosted since there are holiday/vacation-heavy times where the author/reviewers may be gone for an extended time. 

Maybe the answer there is "they reopen the issue and say they'd been on vacation," or "make the auto-close at 4 weeks, with a bot-warning at 3."

I don't really like automerge because it defaults to "code that must be fed and watered forever is now in `devel` yay!" but the time limit is a good way to prevent endless review bikeshedding.

**Comment by bcoca** [comment]
The author being on vacation will only influence when he will start complaining about the close, the auto-close is to push 'committers' (which should not all vacation at same time). 

The author will have no control over it, other than harassing committers.

**Comment by bcoca** [comment]
the 'endless review bickeshedding' is not prevented by this as it requires a 'shipit' for a period of time, if revisions are requested, the shipit label should be removed.

**Comment by gregdek** [comment]
It's true that the review bikeshedding shouldn't be affected. It's perfectly ok to say "this isn't ready for merge for X reasons," so long as X reasons are clear and documented.

If we auto-close a shipit, it will have to be with the message "the core team hasn't had time to review this change."  Then what?  Then the submitter reopens so it can go through the process again and wait two more weeks?  I don't see the benefit of that approach.

The whole point of coming up with an "SLA" that we can actually agree upon (and maybe SLA is too strong a term). If we can agree that an SLA of n weeks is reasonable, we can then certainly come up with escalations / forcing functions that don't involve auto-merge or auto-close. 

For example: every core meeting could start with shipits that are over the two-week limit.

**Comment by bcoca** [comment]
@gregdek agreed, I think that is a better solution than any 'autoresolving' of the ticket.

I would argue that any 'shipit' over a week would normally be a red flag. Sans 'release freeze' and/or end of year vacation period.

**Comment by gregdek** [comment]
@bcoca if the problem is that some of these shipits are sitting around because the core team doesn't feel comfortable merging them -- "this PR doesn't technically break guidelines, but there's something about it that's icky" -- then the simplest solution is to be transparent and say "this PR doesn't technically break guidelines, but there's something about it that's icky."  And then it's a perfect candidate to be discussed at a core meeting. 

To be clear, not that many shipits make it beyond a week, so this is not a crisis. We're just looking for ways to tighten up.

**Comment by gregdek** [comment]
I'm closing this with the recommendation that "old shipits" be added as a regular agenda item for the core meeting.
