### ISSUE TITLE
Close Docker PRs

### ISSUE THREAD

**Issue by gregdek** [ansible/community#82]
We're very close to landing new Docker modules, which means that when we get close enough, we need to close the open PRs against the existing Docker modules.

**Comment by robynbergeron** [comment]
Okay, so - this brings up a lot of questions for me:

* is the plan to immediately deprecate the existing docker module?

* if so, what is the communication plan around that?

either way: 

I have to expect a bunch of folks will continue using the existing docker module for some time - given that it is referenced by and used in one zillion blogs / repos / etc. all over the internet. 

Could we 
* perhaps make a "community best effort" to at least merge existing PRs (at least those that are fixes and not enhancements), with a cutoff of "by some certain date in the future", and just have PR bot stop accepting new requests either now or really soon?
* add a note to the existing docker module saying "deprecating soon, no new PRs accepted"?
* add a warning to ansible / docker.py warning folks that it will be / is deprecated, plz migrate to new thing?

My concerns are (a) the large # of folks using the existing modules, and if / how long they may use the old ones as the new ones get fine-tuned / more well-tested; (b) the large volume of content referencing these modules in blogs/code - which also serve as examples for new folks, and having them suddenly not work is not a great ansible user experience - and a comparitively lacking in volume source of new examples using the new modules (this is just a matter of time, and likely can be accelerated by some outward noise / marketing); (c) not a huge fan of "closing this pr because there are new modules" when we really should have notated those plans in the existing module somehow, and since the plan likely wasn't super obvious to anyone only casually participating, and because ppl will likely be using these for at least a little longer until we set a firm deprecation date. (Which, for all the reasons above, I hope is not immediate, or is at least tied to "new releases moving forward are new-docker only," which I assume is the case.)

But not demoralizing folks who submitted PRs - especially just bugfixes - is my big concern here, even if it turns out that we have to figure out how to backport just a set of PRs for the existing module. Not everyone will move immediately -- esp. folks who have this woven into their production work flow -- and if we can get small fixes in for a "last release" I think we should do that. 

</soapbox> ;)

**Comment by gregdek** [comment]
There is an existing deprecation process that will allow users to use the old Docker module for quite a while yet. Existing playbooks won't break.

At some point, though, we need to send an unambiguous message that it's time to move forward, and that we won't be duplicating effort by maintaining old modules. There's a reason this Docker module is being deprecated, after all.

When this happens will be a result of tomorrow's core meeting.

**Comment by gregdek** [comment]
This is way out of date. Still a concern, of course. Will be part of the Container SIG charter.
