### ISSUE TITLE
commits after "shipit", put PR back in review

### ISSUE THREAD

**Issue by resmo** [ansible/community#91]
From time to time we see PR received a "shipit" from the maintainers, so the bot marked it for inclusion. 

While reviewing for the merge, I see commits after the "shipit". IMHO in this case the PR should get back to review since the maintainer was completely left off of reviewing the new code. To me this looks obvious but is quite important.

Having a pending PR for the bot: https://github.com/ansible/ansibullbot/pull/61

**Comment by dagwieers** [comment]
The problem here is that it will result in contributors not  adding commits once they have received a 'shipit', whereas often these later commits are related to documentation and code comments (at least in my case). If this causes the PR to go back into review mode, I won't bother doing any tidying up once the first 'shipit' is added.
